name: Forge Tests (PR)

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout non-transparent-proxy private submodule
        env:
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
        shell: bash
        run: |
          mkdir $HOME/.ssh
          echo "$SSH_KEY_NTP" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git submodule update --init --recursive modules/non-transparent-proxy

      - name: Install submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Run Forge tests
        run: ./scripts/test.sh -p deep
